
version: 2

models:
    - name: model01
      description: "A starter dbt model"
      columns:
          - name: id
            description: "id is The primary key for this table"
            tests:
                - unique
                - not_null

    - name: model02
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null